export type { Form } from './form'
export type { Document } from './document'
export type { Result } from './result'
export type { SolrPiResults } from './solrPiResults'
export type { SolrPiSearch } from './solrPiSearch'
export type { Suggestions } from './suggestions'
